version: '3.8'

services:
  search:
    image: opensearchproject/opensearch
    environment:
      - node.name=opensearch-stack-1
      - cluster.initial_master_nodes=opensearch-stack-1
    networks:
      - opensearch-stack
    ports:
      - "9201:9200"

  dashboards:
    image: opensearchproject/opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=https://search:9200
    networks:
      - opensearch-stack
    ports:
      - "5602:5601"

networks:
  opensearch-stack:
